Update environment.yml
Trying to fix the binder Docker error:

Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python=3.6.7 -> sqlite[version='>=3.25.2,<4.0a0']
  - sqlite=3.20.1
Use "conda search <package> --info" to see the dependencies for each package.

I switched the sqlite line to:
 - sqlite>=3.25.2