Update environment.yml
Now I'm getting:

Solving environment: ...working... failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - curl=7.58.0
  - python=3.6.7
  - tk=8.6.8
Use "conda search <package> --info" to see the dependencies for each package.

So, just trying to use the binder example environment from here:

https://github.com/binder-examples/conda